repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        exclude: ^infra/.*\.yaml$
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v1.40.0
    hooks:
      - id: cfn-lint
        files: ^infra/.*\.yaml$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4 # Ruff version.
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      - id: ty
        name: ty
        entry: ty check --python .venv/s3fetch
        language: python
        types: [python]
        pass_filenames: false
        additional_dependencies: [ty]
  - repo: https://github.com/PyCQA/bandit
    rev: "1.8.6"
    hooks:
      - id: bandit
        exclude: ^tests/
